name: ECS Deploy Pipeline

on:
push:
branches:
- main

env:
AWS_REGION: ap-south-1
ECR_REPOSITORY: ecs-node-app
ECS_CLUSTER: ecs-node-cluster
ECS_SERVICE: ecs-node-service
ECS_TASK_DEFINITION: ecs-node-app-task

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:

- name: Checkout Code
  uses: actions/checkout@v4

- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: arn:aws:iam::562613557061:role/github-actions-ecs-deploy
    aws-region: ${{ env.AWS_REGION }}

- name: Login to ECR
  uses: aws-actions/amazon-ecr-login@v2

- name: Build Docker Image
  run: |
    docker build -t $ECR_REPOSITORY:${{ github.sha }} ./app

- name: Install Trivy
  run: |
    sudo apt-get install wget -y
    wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
    sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

- name: Scan Docker Image
  run: |
    trivy image $ECR_REPOSITORY:${{ github.sha }}

- name: Tag Image
  run: |
    docker tag $ECR_REPOSITORY:${{ github.sha }} \
    562613557061.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

- name: Push Image to ECR
  run: |
    docker push 562613557061.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

- name: Update ECS Service
  run: |
    aws ecs update-service \
    --cluster $ECS_CLUSTER \
    --service $ECS_SERVICE \
    --force-new-deployment
```
